PACKAGE_NAME="samsung-galaxybook-hotkey"
PACKAGE_VERSION="0.2"

BUILT_MODULE_NAME[0]="samsung-galaxybook"
DEST_MODULE_LOCATION[0]="/updates/dkms"
AUTOINSTALL="yes"

MAKE[0]="make -C /usr/lib/modules/${kernelver}/build M=${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build modules"
CLEAN="make -C /usr/lib/modules/${kernelver}/build M=${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build clean"
